# Generated by Django 5.0.6 on 2024-06-11 16:07

from django.db import migrations


def update_users_with_null_password(apps, schema_editor):
    User = apps.get_model('users', 'User')
    users_with_null_password = User.objects.filter(password__isnull=True)
    for user in users_with_null_password:
        user.set_password('temp_password')  # Asigna un password predeterminado
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(update_users_with_null_password),
    ]
