# Generated by Django 5.0.6 on 2024-06-25 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pets',
            name='type_of_pet',
        ),
    ]
