"""
URL configuration for the authentication system
"""
from django.urls import path, include
from rest_framework import routers
from . import views

"""
Router configuration
"""
router = routers.DefaultRouter()

"""
Registers the UserViewSet with the router, using the basename 'breed'.
This will create the following URLs:
    - /breed/ (GET, POST)
    - /breed/{pk}/ (GET, PUT, PATCH, DELETE)
    - /login/ (POST)
"""
router.register(r'', views.BreedViewSet, basename='breed')


"""
URL patterns
    Includes the URLs generated by the router.
    This will include the URLs for the UserViewSet.
"""
urlpatterns = [
    path('', include(router.urls)),
]
