"""
URL configuration for the authentication system
"""
from django.urls import path, include
from rest_framework import routers
from . import views

"""
Router configuration
"""
router = routers.DefaultRouter()

"""
Registers the UserViewSet with the router, using the basename 'type-of-pet'.
This will create the following URLs:
    - /type-of-pet/ (GET, POST)
    - /type-of-pet/{pk}/ (GET, PUT, PATCH, DELETE)
"""
router.register(r'', views.TypeOfPetViewSet, basename='type-of-pet')


"""
URL patterns
    Includes the URLs generated by the router.
    This will include the URLs for the UserViewSet.
"""
urlpatterns = [
    path('', include(router.urls)),
]
