"""
URL configuration for the authentication system
"""
from django.urls import path, include
from rest_framework import routers
from . import views

"""
Router configuration
"""
router = routers.DefaultRouter()

"""
Registers the UserViewSet with the router, using the basename 'users'.
This will create the following URLs:
    - /users/ (GET, POST)
    - /users/{pk}/ (GET, PUT, PATCH, DELETE)
    - /login/ (POST)
"""
router.register(r'users', views.UserViewSet, basename='users')
router.register(r'login', views.LoginViewSet, basename='login')


"""
URL patterns
    Includes the URLs generated by the router.
    This will include the URLs for the UserViewSet.
"""
urlpatterns = [
    path('', include(router.urls)),
]
