# Generated by Django 5.0.6 on 2024-06-12 14:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('type_of_pet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('type_of_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='type_of_pet.typeofpet')),
            ],
        ),
    ]
